"""MolecularIQ atom-count-v1, an explicitly restricted source-row population."""
import argparse
import hashlib
import json
import random
import shutil
from pathlib import Path

import pyarrow.parquet as pq
from rdkit import Chem, rdBase

ROOT = Path(__file__).resolve().parent
DATA_SHA = '00539423f440a6e02524a8a995a0ddb77c0f525505de53a8dd4105f60e78bfc6'
SEED = 20261009
DEFINITIONS = {
    'carbon_atom': 'Number of atoms with atomic number 6.',
    'hetero_atom': 'Number of atoms whose atomic number is neither 1 nor 6.',
    'halogen_atom': 'Number of F, Cl, Br, or I atoms (not other group-17 elements).',
    'heavy_atom': 'Number of atoms with atomic number greater than 1.',
    'chain_termini': 'Number of carbon atoms with graph degree exactly 1, including ring-attached terminal carbons.',
    'branch_point': 'Number of carbon atoms with graph degree at least 3, including ring atoms; bond order does not affect degree.',
}
CONTRACT = {
    'id': 'moleculariq-atom-count-v1-rdkit-2025.09.4',
    'scope': 'Six scalar atom-count features only; not full MolecularIQ.',
    'eligibility': 'task_type=count, multi_task_load=1, features=single_count_<one of six declared features>. No label/value/parseability/agreement filtering.',
    'features': DEFINITIONS,
    'semantics': 'Parse metadata.smiles with RDKit 2025.09.4 default MolFromSmiles. Ordinary removable explicit H is removed; isotopic H is retained. Degree counts retained atom neighbors. Use presented SMILES, not original_smiles.',
    'finite_domain': 'Exactly one requested property key, integer in [0,N], N=parsed graph atom count. Each property counts a subset of its atoms.',
    'serialization': 'Bare UTF-8 JSON object in /app/answer.json, no tags/prose. Reject duplicate/extra/wrong keys, bools, floats, NaN, infinity, oversized files. Declared Harbor serialization change.',
    'sampling': 'Python random.Random(20261009).sample over UID-sorted complete eligible source rows, 100 without replacement. Repeated molecules retained; no independence claim.',
    'failure_policy': 'Retain all selected rows, never replace or relabel. Zero automated retries. Future infrastructure retries must use the same frozen tasks and be reported separately.',
    'disclosure': 'Generated by an AI agent (OpenHands) on behalf of the user.',
}
DOCKER = '''FROM python:3.13-slim
RUN pip install --no-cache-dir rdkit==2025.9.4
WORKDIR /app
'''
CONFIG = '''schema_version = "1.4"
artifacts = ["/app/answer.json"]
[task]
name = "moleculariq/{name}"
[metadata]
contract = "moleculariq-atom-count-v1-rdkit-2025.09.4"
[agent]
timeout_sec = 900.0
network_mode = "allowlist"
allowed_hosts = ["llm-proxy.app.all-hands.dev"]
[verifier]
timeout_sec = 60.0
environment_mode = "separate"
network_mode = "no-network"
[environment]
build_timeout_sec = 900.0
cpus = 1
memory_mb = 2048
storage_mb = 4096
'''


def dump(path, value):
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + '\n')


def freeze(source, output):
    if rdBase.rdkitVersion != '2025.09.4':
        raise RuntimeError('RDKit 2025.09.4 required')
    if hashlib.sha256(source.read_bytes()).hexdigest() != DATA_SHA:
        raise ValueError('source pin mismatch')
    rows = pq.read_table(source).to_pylist()
    eligible = sorted((r for r in rows if r['task_type'] == 'count'
                       and r['multi_task_load'] == 1
                       and r['features'] in {'single_count_' + f for f in DEFINITIONS}),
                      key=lambda r: r['uid'])
    output.mkdir(parents=True, exist_ok=False)
    # Freeze before inspecting answer values or molecular parsing outcomes.
    public = [{k: r[k] for k in ('uid', 'features', 'question', 'metadata')} for r in eligible]
    dump(output / 'universe.json', public)
    selected = random.Random(SEED).sample(eligible, 100)
    dump(output / 'sample.json', {'seed': SEED, 'algorithm': 'CPython random.Random.sample',
                                'uids': [r['uid'] for r in selected], 'universe_size': len(eligible),
                                'universe_sha256': hashlib.sha256((output / 'universe.json').read_bytes()).hexdigest()})
    dump(output / 'contract.json', CONTRACT)
    failures = []
    for row in selected:
        try:
            build(row, output / 'tasks' / row['uid'])
        except Exception as exc:
            failures.append({'uid': row['uid'], 'error': repr(exc)})
    dump(output / 'build_failures.json', failures)
    return selected


def build(row, task):
    feature = row['features'].removeprefix('single_count_')
    key = feature + '_count'
    smiles = json.loads(row['metadata'])['smiles']
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError('unparseable SMILES; selected row retained')
    target = json.loads(row['target'])
    if set(target) != {key} or type(target[key]) is not int:
        raise ValueError('source target schema mismatch')
    n = mol.GetNumAtoms()
    if not 0 <= target[key] <= n:
        raise ValueError('source outside finite domain')
    for directory in ('environment', 'solution', 'tests'):
        (task / directory).mkdir(parents=True, exist_ok=True)
    (task / 'environment/Dockerfile').write_text(DOCKER)
    (task / 'task.toml').write_text(CONFIG.format(name=row['uid']))
    instruction = (f"# Molecular graph counting\n\n{row['question']}\n\nPresented SMILES: `{smiles}`\n\n"
                   f"Contract: {CONTRACT['id']}. {DEFINITIONS[feature]}\n{CONTRACT['semantics']}\n\n"
                   f"Write only {{\"{key}\": <integer>}} to /app/answer.json, integer in [0,{n}]. "
                   "No tags, prose, floats, or extra keys. RDKit is installed. Do not seek benchmark keys or prior solutions.\n"
                   "You have a working budget of 40 turns. Complete the task and write the required file within those 40 turns.\n")
    (task / 'instruction.md').write_text(instruction)
    dump(task / 'tests/reference.json', {'key': key, 'value': target[key], 'upper_bound': n})
    shutil.copyfile(ROOT / 'verifier.py', task / 'tests/verify.py')
    (task / 'tests/test.sh').write_text('#!/bin/sh\nexec python3 -I /tests/verify.py\n')
    (task / 'solution/solve.sh').write_text("#!/bin/sh\ncat > /app/answer.json <<'ANSWER'\n" + json.dumps(target) + '\nANSWER\n')
    for file in ('tests/test.sh', 'solution/solve.sh'):
        (task / file).chmod(0o755)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--source', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    freeze(args.source, args.output)
